# Generated by Django 3.0.6 on 2020-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='mobile_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobile_phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
