# Generated by Django 3.0.6 on 2020-06-30 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('passport', models.IntegerField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(default='/static/default_img/default.png', upload_to='images/avatars/%Y/%m/%d/')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полный адрес')),
                ('diagnose', models.CharField(blank=True, max_length=50, null=True, verbose_name='Диагноз')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('passport', models.IntegerField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(default='/static/default_img/default.png', upload_to='images/avatars/%Y/%m/%d/')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полный адрес')),
                ('working_experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Опыт работы')),
                ('appointments_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specialty', models.CharField(max_length=20, verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
