# Generated by Django 3.0.6 on 2020-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='patient',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
