# Generated by Django 3.0.6 on 2020-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200614_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointments_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
