# Generated by Django 3.0.6 on 2020-07-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200706_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='timeslot',
        ),
    ]
