# Generated by Django 3.0.6 on 2020-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
