# Generated by Django 3.0.6 on 2020-06-06 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psy_tests', '0004_auto_20200606_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(1, 'one_answer'), (2, 'multi_answer'), (3, 'text_answer')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
