# Generated by Django 3.0.6 on 2020-06-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_tests', '0005_auto_20200606_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytest',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Вопрос'),
        ),
    ]
