# Generated by Django 3.0.6 on 2020-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_tests', '0008_auto_20200606_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('one_answer', 'one_answer'), ('multi_answer', 'multi_answer'), ('text_answer', 'text_answer')], max_length=15, null=True),
        ),
    ]
