# Generated by Django 3.0.6 on 2020-06-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psy_tests', '0009_auto_20200606_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='variant',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
